### ISSUE TITLE
Does this library support MAUI for Mac use?

### ISSUE THREAD

**Issue by pjy612** [MonoMod/MonoMod#105]
### Description
Try to use it in the Maui Mac environment, but an error is displayed.

The Windows environment works properly.

![Snipaste_2022-09-13_09-26-59](https://user-images.githubusercontent.com/4072526/189787519-f7832dc3-0456-4775-a6e1-1fe04436588a.png)

**Comment by nike4613** [comment]
If you're running on an M1 and not through Rosetta, then MonoMod does not support that configuration. It should support running through Rosetta though.
