### ISSUE TITLE
The code doesn't have any comments

### ISSUE THREAD

**Issue by andywu188** [MonoMod/MonoMod#68]
Thank you for the tools, but  I cannot understand their meaning and usage. Because all classes, methods and members  are not commented.

**Comment by 0x0ade** [comment]
MonoMod is my first long term C# project, which started out over 5 years ago. I never expected so many people to use MonoMod.

Sadly I don't have the time to document all the things right now.

**Comment by pardeike** [comment]
Personally, I think the code is reasonably clean and self documenting. The times I had questions I was able to answer them by simply looking at the source.
