### ISSUE TITLE
Stub .ctor with [MonoModIgnore] still being patched?

### ISSUE THREAD

**Issue by Kein** [MonoMod/MonoMod#70]
I have a class structure like that:

```cs
public class GUILayoutUtility
{
    static GUILayoutUtility() { //static ctor}
    internal sealed class LayoutCache
    {
        //ctors and vars
    }
}

// multiple other classes referenced in the class data above
internal class GUILayoutEntry, etc
{
}
```
Because they are all internal I cannot reference them so I create stubs with `[MonoModIgnore]`

```cs
[MonoModIgnore]
internal sealed class LayoutCache
{
	[MonoModIgnore]
	somefield
}
```
Original looks like this:
![image](https://user-images.githubusercontent.com/623756/93249635-4aca0800-f79a-11ea-8b6f-253c67153f4c.png)

And patched looks like this:
![image](https://user-images.githubusercontent.com/623756/93249663-54ec0680-f79a-11ea-9cf1-93fce4aa7de9.png)

What gives and how can I avoid this?

**Comment by fifty-six** [comment]
IL-wise the two images you posted are the same, this just looks like a quirk with your decompiler. Field initialization is performed in the constructors.
