### ISSUE TITLE
a little code issue

### ISSUE THREAD

**Issue by a2659802** [MonoMod/MonoMod#77]
In **MonoMod.RuntimeDetour.Hook.cs** line 52-54. 

```csharp
if (target == null && !to.IsStatic) {
	throw new InvalidOperationException($"Hook for method {from} must be static, or you must pass a target instance.");
}
```

it check the "to" paramemter but the Exception message BUT throw the "from" paramemter, should be miswrote i think

**Comment by nike4613** [comment]
That message is correct.  It is saying that the patch for 'from' (the method being patched) must be static, where the subject is "patch" (or "hook" in the actual message), not 'from'.
