### ISSUE TITLE
Correct the rain world entry: We use BepinEx and a custom manager instead of partiality now

### ISSUE THREAD

**Issue by kuvithanol** [MonoMod/MonoMod#82]
this contains some partiality code in it for backwards compatibility, but partiality itself is deprecated and will no longer be used.

**Comment by harbingerofme** [comment]
Please correct the PR if you have a better description for how you use MonoMod

**Comment by sovietsamuelson** [comment]
Ill contact a more experienced modder to submit a correction, thank you

**Comment by Dual-Iron** [comment]
It's BepInEx bundled with a patcher that fixes deprecated HookGen references and a plugin that loads Partiality mods. New mods are encouraged to be BepInEx plugins, but Partiality is supported for backwards compatibility—until Rain World itself introduces breaking changes, that is.

I think using `Rain World: RainDB via modified BepInEx` is fair enough. There isn't a repository for this modified version, but a ZIP can be downloaded from [here](https://beestuff.pythonanywhere.com/audb/api/v2/bepinex/download).

**Comment by FyreByrns** [comment]
Another experienced Rain World modder here, I agree entirely with what @Dual-Iron says.
