### ISSUE TITLE
Detouring under .NET 7 is not supported

### ISSUE THREAD

**Issue by ghorsington** [MonoMod/MonoMod#94]
### Description

Currently applying detours under the upcoming .NET 7 is not working. Based on an investigation in https://github.com/BepInEx/HarmonyX/pull/49, .NET 7 Preview 3 is likely the culprit as there all Harmony patching tests fail.
This could probably have something to do with changes to how tiered compilation is done ([see .NET 7 Preview 3 changelog](https://github.com/dotnet/core/issues/7108#issuecomment-1085035677)).

### Example

Download .NET 7 Preview 4 and retarget `MonoMod.UnitTest` to `net7.0`. Then, run all tests (specifically any runtime detouring, like `HookTest.TestHooks`).
No errors are generated, but the hook is not invoked when the original method is called. I did not yet check the generated ASM code.

**Comment by nike4613** [comment]
I'll take a look at it at some point, .NET 7 not working is not surprising. I suspect that it shouldn't require *too* major of changes.

**Comment by nike4613** [comment]
.NET 7 is fully supported by the `reorganize` branch, if you are able to start using that. I'd also like more users, so I can get a better idea of what all is left for full feature parity with the old codebase.

**Comment by evaanp** [comment]
Can confirm that starting from version 22.11.4-prerelease of the reorganize branch, the exception stating that .net 7 is not supported is gone.

The issue however, is still present. Even when running with a debugger attached, which was working before with the latest nuget package of the main branch, the hooks are not invoked.

**Comment by nike4613** [comment]
Have you tested using the latest builds on NuGet?

**Comment by evaanp** [comment]
Yes, version 23.3.22.1

**Comment by nike4613** [comment]
Could you open a new issue for this? When you do, please make sure to include arch, OS, and the methods that are causing problems.

**Comment by evaanp** [comment]
Excuse me. I tried reproducing it in an isolated environment, and couldn't; it was working fine. What i essentially did was create a new Hook object, without storing a reference to it. This worked fine in the version on the Main branch, but not in the new reorganize version (or with the new .NET version). I guess the Hook got garbage collected immediately after instantiating it, breaking my detour. When i created a reference for all my hooks, the code was working again.

**Comment by nike4613** [comment]
That behavior is by design. Hook lifetimes are tied to the hook objects themselves. If that object is collected, the associated detour is as well.

**Comment by SvetlovA** [comment]
For me .net7 started to work on all platforms, thanks. But .NET Framework hooking was broken. Now it's throwing an exception `System.NotImplementedException : The method or operation is not implemented.` when I'm trying to hook generic method StackTrace:
```
System.NotImplementedException : The method or operation is not implemented.
   at MonoMod.Core.Interop.Fx.V48.MethodTable.GetMethodDescForSlot(UInt32 slotNumber)
   at MonoMod.Core.Interop.Fx.V48.MethodDesc.FindTightlyBoundWrappedMethodDesc(MethodDesc* pMD)
   at MonoMod.Core.Platforms.Runtimes.FxCLR4Runtime.GetMethodEntryPoint(MethodBase method)
   at MonoMod.Core.Platforms.PlatformTriple.GetNativeMethodBody(MethodBase method)
   at MonoMod.Core.Platforms.PlatformTripleDetourFactory.Detour.CreateDetour()
   at MonoMod.Core.Platforms.PlatformTripleDetourFactory.DetourBase.Apply()
   at MonoMod.RuntimeDetour.DetourManager.RootManagedChainNode.UpdateDetour(IDetourFactory factory, MethodBase fallback)
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.UpdateChain(IDetourFactory updatingFactory, Boolean& stealTrampolines)
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.AddDetour(SingleManagedDetourState detour, Boolean takeLock)
   at MonoMod.RuntimeDetour.Hook.Apply()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, MethodInfo target, Object targetObject, IDetourFactory factory, DetourConfig config, Boolean applyByDefault)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, MethodInfo target)
```
Will it be implemented in the future version? Or it's not possible to hook generic methods for .NET Framework?

**Comment by nike4613** [comment]
Hooking generic methods has never been supported on any runtime. It has always been a matter of "if it works for you, great, I guess", not actual support. Generic hooks are basically always incredibly fragile; it just so happens that reorg does a *lot* more checks around them for .NET Framework than before.

**Comment by nike4613** [comment]
As of yesterday, MonoMod.RuntimeDetour v25.0.0 and MonoMod.Core v1.0.0 fix this.
